### ISSUE TITLE
Method not found: 'TestFairyHttpOverrides'

### ISSUE THREAD

**Issue by mnesarco** [testfairy/testfairy-flutter#20]
Hi Friends,
I have followed your migration guide here: https://github.com/testfairy/testfairy-flutter#how-to-compile-with-latest-unreleased-flutter
but now i get this error:

```
../testfairy-flutter-master/lib/testfairy.dart:459:16: Error: Method not found: 'TestFairyHttpOverrides'.
    return new TestFairyHttpOverrides();
               ^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by mnesarco** [comment]
This is very strange, the file **network_logging.dart** in the cloned directory is empty, but the github version is not. Same happens if I download the zip version.

**Comment by mnesarco** [comment]
The problem is that your sed commands:

```
sed  "s/Modern Flutter \*\*/\//" lib/src/network_logging.dart > lib/src/network_logging.dart
sed  "s/\*\* Modern Flutter/\//" lib/src/network_logging.dart > lib/src/network_logging.dart

```
Deletes all the content of the file **network_logging.dart**

**Comment by diegoperini** [comment]
Hi @mnesarco ,

Thanks for notifying us with the issue. Some shells might create output files before the command is processed, that may cause an issue with this approach. Can you retry with the following commands?

```shell
sed  "s/Modern Flutter \*\*/\//" lib/src/network_logging.dart > lib/src/network_logging.temp
sed  "s/\*\* Modern Flutter/\//" lib/src/network_logging.temp > lib/src/network_logging.dart
rm -rf lib/src/network_logging.temp
```

**Comment by mnesarco** [comment]
Hi @diegoperini ,
I removed the comments by hand, then other problems appeared so I just downgrade flutter version to 1.20 and left the unmodified version.

**Comment by diegoperini** [comment]
I see. Flutter's master channel can be unstable and given workaround is not expected to work in every setup out there. I suggest people having similar problems switch to stable channel for the time being.
