### ISSUE TITLE
Testfairy Flutter docs have wrong import

### ISSUE THREAD

**Issue by hapasa** [testfairy/testfairy-flutter#41]
Fyi, your docs and examples for flutter have wrong code:

import 'package:testfairy_flutter/testfairy.dart';

it should be

import 'package:testfairy_flutter/testfairy_flutter.dart';

https://www.testfairy.com/frameworks/flutter lacks the import altogether, should be in step 3.
https://docs.testfairy.com/Platforms/Flutter.html has the wrong path in step 3.

**Comment by diegoperini** [comment]
@hapasa thank you for this discovery. I'm fixing the docs with the correct `import` statement.
