### ISSUE TITLE
The named parameters onError and zoneSpecification not defined

### ISSUE THREAD

**Issue by samueladekunle** [testfairy/testfairy-flutter#5]
Hello, I try to compile the code in the example folder, but I see errors on lines 32, and 33.

The errors have to do with the `onError`, and `zoneSpecification` parameters, not being defined in `HttpOverrides.runWithHttpOverrides()` method.

```
HttpOverrides.runWithHttpOverrides(
      () async {
        try {
          FlutterError.onError =
              (details) => TestFairy.logError(details.exception);

          // Call `await TestFairy.begin()` or any other setup code here.

          runApp(TestfairyExampleApp());
        } catch (error) {
          TestFairy.logError(error);
        }
      },
      TestFairy.httpOverrides(),
      onError: TestFairy.logError, // Line 32
      zoneSpecification: new ZoneSpecification( //Line 33
        print: (self, parent, zone, message) {
          TestFairy.log(message);
        },
      )
  );
```

**Comment by diegoperini** [comment]
Hi @samueladekunle ,

Can you verify that it is not an import problem by checking for the following imports below in your dart file?

https://github.com/testfairy/testfairy-flutter/blob/master/example/lib/main.dart#L1-L7

**Comment by samueladekunle** [comment]
Hello @diegoperini ,

I cannot see any import problem, I basically just cloned the repo, and opened the example folder, in my IDE.

Here's a screenshot

![image](https://user-images.githubusercontent.com/27623752/83918111-0036f980-a770-11ea-9efd-ec5f82b8b476.png)

The blue squiggly lines on lines 2 to 5, have to do with how import statements should be arranged in a dart file, and nothing to do with the errors.

**Comment by diegoperini** [comment]
Thanks for the quick response to my silly question. :)

Apparently, sometime along the line, Flutter changed the signature for `HttpOverrides.runWithHttpOverrides()`. We'll look into it.

In the meantime, if you have a working hack, feel free to share as long as this issue stays open.

**Comment by samueladekunle** [comment]
Okay @diegoperini,

I will, provided I have a solution.

And BTW, your question was not silly :)

Thank you for taking the time to review the issue.

**Comment by diegoperini** [comment]
Hi @samueladekunle ,

Can you try `cd example; flutter build apk` and tell me if it can build an apk? If it can't, can you paste the error here as well?

I've tried it on my Mac but neither the static analysis nor the build fails. Maybe there is a difference in our Android Studio configurations which creates the problem. Just to be safe, can you also run `flutter doctor` to see if there are other missing components in your Flutter installation?

**Comment by samueladekunle** [comment]
Hello @diegoperini, 

I still get the errors on the editor (VSCode).

When I ran `flutter build apk`, this was the message I got:

```
Compiler message:
lib/main.dart:32:7: Error: No named parameter with the name 'onError'.
      onError: TestFairy.logError,
      ^^^^^^^
org-dartlang-sdk:///third_party/dart/sdk/lib/_http/overrides.dart:65:12: Context: Found this candidate, but the arguments don't match.
  static R runWithHttpOverrides<R>(R body(), HttpOverrides overrides) {
           ^^^^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Development\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 882

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'C:\Development\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 56s
Running Gradle task 'assembleRelease'...

Running Gradle task 'assembleRelease'... Done                     120.4s (!)
Gradle task assembleRelease failed with exit code 1
```

This is the output of `flutter --version`:
```
Flutter 1.17.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f7a6a7906b (5 weeks ago) • 2020-05-12 18:39:00 -0700
Engine • revision 6bc433c6b6
Tools • Dart 2
```

This is the output of `flutter doctor -v`:
```
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18363.900], locale en-NG)
    • Flutter version 1.17.1 at C:\Development\flutter
    • Framework revision f7a6a7906b (5 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Samuel\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.46.0)
    • VS Code at C:\Users\Samuel\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[√] Connected device (1 available)
    • Infinix X572 • 10.196.181.195:5555 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```

**Comment by diegoperini** [comment]
Hi @samueladekunle ,

Thank you for your patience. We have a patch for the issue but before publishing it, I'd be honored if you tried it yourself. [This](https://github.com/testfairy/testfairy-flutter/blob/bugfix-zoned-httpoverrides/example/lib/main.dart) is the new setup code, no other change is needed.

**Comment by samueladekunle** [comment]
Hello @diegoperini ,

I have tested the branch out, and I no longer see the errors.

![image](https://user-images.githubusercontent.com/27623752/85564131-e75e8d00-b625-11ea-8acc-2e0be84ef16d.png)

Thank you for the swift turnaround.

**Comment by diegoperini** [comment]
Amazing. We will be publishing a new release in the following hours. I will update the readme to reflect the latest changes. Please revisit the readme file once you pull the changes.

**Comment by diegoperini** [comment]
Hi @samueladekunle ,

We've releases a new plugin under version 1.0.9. Please review README.md for latest integration instructions. Feel free to create a new issue if anything goes wrong. Thank you for being here and helping me find out what went wrong. <3
